spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurantero?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Bogota
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5120MB
      max-request-size: 10240MB
server:
  servlet:
    context-path: /restaurantero/api
  port: 8080

restaurantero:
  jwt:
    secret-key: 413F4428472B4B6250655368566D5971337336763979244226452948404D635166546A576E5A7234753777217A25432A462D4A614E645267556B587032733576
    expiration-token-hours: 14
    application-name: RESTAURANTERO